config/routes.rb
Rails.application.routes.draw do

  resources :cars

  devise_for :users
  root to: 'cars#index'

  resources :rents do
    member do
      get 'return'
    end
  end
  
  resources :clients
  resources :wizard_cars

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  #before_validation :create_brand_from_name

  has_many :models

  validates :brand_name, presence: true
  validates :brand_name, uniqueness: true

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :model
  has_many :rents
  has_many :clients, through: :rents

  validates :model_id, presence: true 
  validates :registration_no, presence: true
  validates :year_of_manufacture, presence: true, numericality: {
    greater_than_or_equal_to: 1990, 
    less_than_or_equal_to: Time.now.year.to_i
  }
  validates :mileage, presence: true, numericality: {greater_than: 0}


  state_machine initial: :available do
    state :available
    state :rented
    state :serviced

    event :rent do
      transition :available => :rented
    end

    event :service do
      transition :available => :serviced
    end

    event :return do
      transition :rented => :available
    end

    event :fixed do
      transition :serviced => :available
    end


  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :rents
  has_many :cars, through: :rents



  validates :name, :surname, :age, :document_no, :document_type, presence: true
  
#  validates :document_type inclusion
  
  
  validates :age, numericality: true, inclusion: {in: 18..100}
  validates :name, uniqueness: true

end

app/models/model.rb
class Model < ActiveRecord::Base
  has_many :cars
  belongs_to :brand
  
  validates :model_name, presence: true, uniqueness: true
  validates :brand, :associated => true
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :client
  belongs_to :car
  
  validates :client_id, :car_id, presence: true, numericality: {greater_than: 0}


  scope :active, lambda {where(return_date: nil)}
  scope :inactive, lambda {where.not(return_date: nil)}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :destroy]

  def index
    @cars = Car.order('state')
  end
  
  def show
  end

  def edit
  end

  def destroy
    @car.destroy
     respond_to do |format|
      format.html { redirect_to root_url, notice: 'Samochód został usunięty' }
      format.json { head :no_content }
    end
  end  

private

  def set_car
    @car = Car.find(params[:id])
  end
  
  def car_params
    params.require(:car).permit(:milage, :registration_no, :year_of_manufacture, :model_id)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]


  def index
    @clients = Client.all
  end

  def show
  end

  def edit
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client, notice: 'Klient został prawidłowo dodany'
    else
      render :new
    end
  end

	def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Klient został prawidłowo zaktualizowany'
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :surname, :age, :document_no, :document_type)
  end

end

app/controllers/new_cars_controller.rb
class NewCarsController < ApplicationController
  include Wicked::Wizard

  steps :new_brand, :new_model , :add_car

  def show
    case step
    when :new_brand
      @brand = Brand.new
    when :new_model
      @model = Brand.find(session["brand_id"]).models.new
    when :add_car
      @car = Model.find(session["model_id"]).cars.new
    end
    render_wizard
  end

  def update
    case step
    when :new_brand
      brand = Brand.create!(brand_params)
      session["brand_id"] = brand.id
      redirect_to wizard_path(:new_model)
    when :new_model
      m = Brand.find(session["brand_id"]).models.create!(model_params)
      session["model_id"] = m.id
      redirect_to wizard_path(:add_car)
    when :add_car
      Model.find(session["model_id"]).cars.create(car_params)
      redirect_to '/'
    end
  end


protected 

  def brand_params
    params.require(:brand).permit(:brand_name)
  end

  def model_params
    params.require(:model).permit(:model_name, :brand_id)
  end

  def car_params
    params.require(:car).permit(:model_id, :mileage, :registration_no, 
      :year_of_manufacture, :state)
  end



end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:return, :update, :edit, :update_return, :destroy]


#before_action :authenticate_user!, :except => [:index] 

  def index
    @rents_active = Rent.active
    @rents_inactive = Rent.inactive
  end

  def new
    @rent = Rent.new
    @car = Car.find(params[:car_id])
  end

  def create
    @rent = Rent.create!(rent_params)
      if @rent.car.state == "available" && @rent.save 
        @rent.car.rent
        redirect_to rents_path, notice: 'Rent was successfully created.'
      else
        render :new
      end
  end

  def update
    if @rent.update(return_params)
      @rent.car.return
      redirect_to rents_path, notice: 'Dokonano zwrotu samochodu'
    else
      render :return
    end

  end

  def return
  end

  def destroy
    @rent.destroy!
    redirect_to rents_path, notice: 'Wypożyczenie usunięte.'
  end

private

  def rent_params
    params.require(:rent).permit(:client_id, :car_id, :plan_return_date)
  end

  def return_params
    params.require(:rent).permit(:return_date)
  end

  def set_rent
    @rent = Rent.find(params[:id])
  end

end

app/controllers/wizard_cars_controller.rb
class WizardCarsController < ApplicationController
  include Wicked::Wizard

  steps :new_brand, :new_model , :add_car

  def show
    case step
    when :new_brand
      @brand = Brand.new
    when :new_model
      @model = Brand.find(session["brand_id"]).models.new
    when :add_car
      @car = Model.find(session["model_id"]).cars.new
    end
    render_wizard
  end

  def update
    case step
    when :new_brand
      brand = Brand.create!(brand_params)
      session["brand_id"] = brand.id
      redirect_to wizard_path(:new_model)
    when :new_model
      m = Brand.find(session["brand_id"]).models.create!(model_params)
      session["model_id"] = m.id
      redirect_to wizard_path(:add_car)
    when :add_car
      Model.find(session["model_id"]).cars.create(car_params)
      redirect_to '/'
    end
  end


protected 

  def brand_params
    params.require(:brand).permit(:brand_name)
  end

  def model_params
    params.require(:model).permit(:model_name, :brand_id)
  end

  def car_params
    params.require(:car).permit(:model_id, :mileage, :registration_no, 
      :year_of_manufacture, :state)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def car_ready(car)
    return true if car.state == "available"
  end

end

app/helpers/cars_helper.rb
module CarsHelper

  def car_state(s)

    if s == "available"
      return "dostępny"
    elsif s == "rented" 
      return "wypożyczony"
    else 
      return "w naprawie"
    end
  end

  def car_rent(car)
    if car_ready(car) == true
      link_to 'Wypożycz', new_rent_path(:car_id => @car.id)
    end
  end


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/new_car_helper.rb
module NewCarHelper
end

app/helpers/rents_helper.rb
module RentsHelper

  def client_datas
    lambda { |client| "#{client.name} #{client.surname} #{client.document_no}"}
  end

  def car_datas
    lambda { |car| "#{car.model.brand.brand_name} #{car.state}"}
  end

  def rent_client_datas(rent)
    "#{rent.client.name} #{rent.client.surname} #{rent.client.document_no}"
  end

  def rent_car_datas(rent)
    "#{rent.car.model.brand.brand_name} #{rent.car.model.model_name} #{rent.car.registration_no}"
  end

end

app/views/cars/_form.html.erb
<%= simple_form_for @car do |f| %>
<%= fields_for(@car, @car.model.build) do |fields|
<%= fields.text_field :model %>
<% end %>
<%= f.text_field :mileage %>
<%= f.text_field :year_of_manufacture %>
<%= f.text_field :registration_no %>
<%= f.text_field :submit %>
<% end %>

app/views/cars/index.html.erb
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>MARKA</th>
        <th>MODEL</th>
        <th>DOSTĘPNOŚĆ</th>
        <th>OPCJE</th>
      </tr>
    </thead>
    <tbody class="table table-striped">
      <% @cars.each do |car| %>
      <tr>
        <td><%= car.model.brand.brand_name %></td>
        <td><%= car.model.model_name %></td>
        <td>
           <%= car_state(car.state) %>
        </td>
        <td><%= link_to 'Usuń', car, method: :delete, data: { confirm: 'Na pewno usunąć?' }, class: "btn btn-danger btn-xs" %>
          <%= link_to 'Szczegóły', car_path(car), class: "btn btn-info btn-xs" %>

        </td>
       
        <% end %>
      </tr>     
    </tbody>
  </table>
  
<%= link_to "Dodaj nowy samochód", wizard_car_path(:new_brand), class: "btn btn-success" %>

app/views/cars/new.html.erb
<h1>Dodaj auto</h1>

  <%= render 'form' %>

app/views/cars/show.html.erb
<h1>Szczegóły samochodu</h1>

<p>Marka: <%= @car.model.brand.brand_name %></p>
<p>Model: <%= @car.model.model_name %></p>
<p>Numer rejestracyjny: <%= @car.registration_no %></hp>
<p>Przebieg: <%= @car.mileage %></p>
<p>Data produkcji: <%= @car.year_of_manufacture %></p>
<p>Dostępność: <%= @car.state %></p>

<%= car_rent(@car) %>
<%= link_to 'Powrót', root_path %>

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>
  <%= f.input :name, label: 'Imię' %>
  <%= f.input :surname, label: 'Nazwisko' %>
  <%= f.input :age, label: 'Wiek' %>
  <%= f.input :document_type, label: 'Rodzaj dokumentu' %>
  <%= f.input :document_no, lable: 'Numer dokumentu' %>
  <%= f.button :submit, lable: 'Potwierdź' %>
<% end %>

app/views/clients/edit.html.erb
<h1>Aktualizacja danych klienta</h1>

<%= render 'form' %>

<%= link_to 'Podgląd', @client %>
<%= link_to 'Powrót', clients_path %>

app/views/clients/index.html.erb
<h1>Lista klientów</h1>

<table class="table table table-striped">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Wiek</th>
      <th>Nr dokumentu</th>
      <th>Typ dokumentu</th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
    <tr>
      <td><%= client.name %></td>
      <td><%= client.surname %></td>
      <td><%= client.age %></td>
      <td><%= client.document_no %></td>
      <td><%= client.document_type %><td>
      <td><%= link_to 'Podgląd', client_path(client) %>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Dodaj nowego klienta', new_client_path %> <br>
<%= link_to 'Powrót', root_path %>

app/views/clients/new.html.erb
<h1>Dodaj nowego klienta</h1>

<%= render 'form' %>

<%= link_to 'Powrót', clients_path %>

app/views/clients/show.html.erb
<h1>Szczegółowy opis klienta</h1>

<h2>Imię: <%= @client.name %> Nazwisko: <%= @client.surname %></h2>
<h3>Wiek: <%= @client.age %></h3>
<h4>Typ dokumentu: <%= @client.document_type %></h4>
<h4>Numer dokumentu: <%= @client.document_no %></h4>

<%= link_to 'Powrót', clients_path %>
<%= link_to 'Usuń klienta', @client, method: :delete, data: { confirm: 'Jesteś pewny?'} %>
<%= link_to 'Edytuj klienta', edit_client_path(@client) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent Car Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <div id='user_header'>
    <%=link_to 'Home', cars_path, :class=>'btn btn-info btn-sm', :type=>'button'%>
    <%if user_signed_in?%>
      Logged in as <%=current_user.email%>
      <%=link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn-default btn-sm", :type=>"button"%>
      <%else%>
        <%=link_to "Sign up", new_user_registration_path, :class => "btn btn-primary btn-sm", :type=>"button"%>
        <%=link_to "Sign in", new_user_session_path, :class => "btn btn-default btn-sm", :type=>"button"%>
      <%end%>
  </div>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/rents/_form.html.erb
<%= simple_form_for @rent do |f| %>

  <%= f.association :client, label_method: client_datas %>
  <%= f.input :plan_return_date, label: 'Planowana data zwrotu' %>
  <%= f.hidden_field :car_id, value: @car.id %>

  <%= f.button :submit %>
<% end %>

app/views/rents/_return_form.html.erb
<%= simple_form_for @rent do |f| %>
  <%= f.input :return_date, label: "Data zwrotu" %>
  <%= f.button :submit %>
<% end %>

app/views/rents/destroy.html.erb
<h1>Rents#destroy</h1>
<p>Find me in app/views/rents/destroy.html.erb</p>

app/views/rents/index.html.erb
<h1>Wypożyczenia otwarte</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Person</th>
      <th>Data wypożyczenia</th>
      <th>Data planowanego zwrotu</th>
      <th>AKCJA</th>
    </tr>
  </thead>
  <tbody>
    <% @rents_active.each do |rent| %>
      <tr>
        <td><%= rent_car_datas(rent) %></td>
        <td><%= rent_client_datas(rent) %></td>
        <td><%= rent.created_at %></td>
        <td><%= rent.plan_return_date %></td>
        <td><%= link_to "Zwrot samochodu", return_rent_path(rent) %></td>
        <td><%= link_to "Usuń wypożyczenie", rent, method: :delete, data: { confirm: 'Jesteś pewny?'}  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br><br>
<h1>Wypożyczenia zamknięte</h1>
<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Person</th>
      <th>Data wypożyczenia</th>
      <th>Data planowanego zwrotu</th>
      <th>AKCJA</th>
    </tr>
  </thead>
  <tbody>
    <% @rents_inactive.each do |rent| %>
      <tr>
        <td><%= rent_car_datas(rent) %></td>
        <td><%= rent_client_datas(rent) %></td>
        <td><%= rent.created_at %></td>
        <td><%= rent.plan_return_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rents/new.html.erb
<h1>Dodaj nowe wypożyczenie</h1>

<%= render 'form' %>

app/views/rents/return.html.erb
<%= render 'return_form' %>

app/views/rents/update.html.erb
<h1>Rents#update</h1>
<p>Find me in app/views/rents/update.html.erb</p>

app/views/wizard_cars/add_car.html.erb
<%= form_for @car, url: wizard_path, method: :put do |f| %>
<br />
<%= f.label 'Podaj przebieg samochodu' %>
<%= f.text_field (:mileage) %>
<br />
<%= f.label 'Podaj numer rejestracyjny samochodu' %>
<%= f.text_field (:registration_no) %>
<br />
<%= f.label 'Podaj rok produkcji samochodu' %>
<%= f.text_field (:year_of_manufacture) %>
<br />
<%= f.submit 'Dodaj samochód' %>
<% end %>

app/views/wizard_cars/new_brand.html.erb
<%= form_for @brand, url: wizard_path, method: :put do |f| %>
<%= f.label 'Podaj markę samochodu' %>
<%= f.text_field (:brand_name) %>
<br />
<%= f.submit 'Dodaj markę' %>
<% end %>

app/views/wizard_cars/new_model.html.erb
<%= form_for @model, url: wizard_path, method: :put do |f| %>
<%= f.label 'Podaj model samochodu' %>
<%= f.text_field (:model_name) %>
<br />
<%= f.submit 'Dodaj model' %>
<% end %>